FROM node:10

RUN mkdir -p /app

WORKDIR /app

COPY package*.json /app

RUN yarn global add @quasar/cli
RUN yarn install
RUN yarn add express serve-static connect-history-api-fallback
RUN yarn run build

CMD [ "yarn", "run", "start"]