FROM python:3.8-buster

WORKDIR /app

RUN apt-get update && apt-get -y dist-upgrade
RUN apt install -y netcat

RUN pip3 install virtualenv

RUN virtualenv env

COPY ./requirements.txt /app/requirements.txt

RUN pip3 install -r requirements.txt

COPY . /app


CMD ["sh", "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:$PORT"]