name: Deploy API

on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gonuit/heroku-docker-deploy@v1.3.2 
      - name: Push Docker to Heroku
        with:
          dockerfile_directory: ./api
          dockerfile_name: dockerfile.prod
          docker_options: "--no-cache"
          process_type: web
          
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_API }}
          
