name: Build Enviroment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and run application (db, back, front)
      run: docker-compose up --build -d
    - name: Test Backend
      run: docker-compose run back python manage.py test 
      
