name: Build Enviroment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build application (db, back, front)
      run: |
          python -m pip install --upgrade pip
          pip install coverage
          docker-compose up --build -d
    - name: Test and coverage Backend
      run: |
            docker-compose run back python manage.py migrate 
            docker-compose run back coverage run manage.py test
    - uses: actions/setup-python@v1
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CodeClimate }}
    - name: Test Frontend
      run: |
            docker-compose run front yarn run test:unit:coverage
