name: Build Enviroment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and run application (db, back, front)
      run: docker-compose up --build -d
    - name: Test Backend
      run: |
            coverage --version
            coverage run docker-compose run back python manage.py test
    - uses: paambaati/codeclimate-action@v2.5.3
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CodeClimate }}
      with:
          coverageCommand: coverage xml
          debug: true
