name: Build Enviroment and test backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build application (db, back, front)
      run: docker-compose build
      
    - name: Test back
      run:  |
            docker start trabalho-individual-2020-2_postgres_1
            docker start trabalho-individual-2020-2_back_1
            docker exec trabalho-individual-2020-2_back_1 9dd0b25d5d9d python manage.py test
    
