name: Build Enviroment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    
    - name: Build and run application (db, back, front)
      run: |
          python -m pip install --upgrade pip
          pip install coverage
          docker-compose up --build -d
    - name: Test Backend
      run: |
            coverage --version
            docker-compose run back coverage run manage.py test
    - uses: paambaati/codeclimate-action@v2.5.3
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CodeClimate }}
      with:
          coverageCommand: coverage xml
          debug: true
    - name: Test Frontend
      run: |
            docker-compose run front yarn run test:unit:coverage
