# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
          image: postgres
          env:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PORT: 5432
            POSTGRES_PASSWORD: postgres
          ports:
            - 5432:5432
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Install Dependencies
          run: |
              python -m pip install --upgrade pip
              pip install virtualenv
              virtualenv env
              pip install flake8 pytest
              if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
        - name: Lint
          run: |
              flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=env
              flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=F401 --exclude=env
        - name: Migrate
          run: python api/manage.py migrate
        - name: Test
          run: |
              coverage --version
              coverage run api/manage.py test api
        - name: Coverage
        - uses: paambaati/codeclimate-action@v2.5.3
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CodeClimate }}
          with:
            coverageCommand: coverage xml
            debug: true

    env:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PORT: 5432
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
    
