# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
          image: postgres
          env:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PORT: 5432
            POSTGRES_PASSWORD: postgres
          ports:
            - 5432:5432
    steps:
        - uses: actions/checkout@master
        - run: python -m pip install --upgrade pip
        - run: pip install virtualenv
        - run: virtualenv env
        - run: pip install flake8 pytest
        - run: if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
        - run: python api/manage.py migrate
        - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=env
        - run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore=F401 --exclude=env
        - run: coverage python api/manage.py test
        - run: coverage report
    env:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PORT: 5432
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        CC_TEST_REPORTER_ID: 2d12e82be4098ee95a47ef26d4af2bdb9e732707bb9aa83cd3d47d7dc5ca8c7a
    
